name: Beta Release (Pull Requests)

on:
  pull_request:
    branches:
      - main
      - staging
    types: [opened, synchronize, reopened]

jobs:
  prepare-beta:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.beta-version.outputs.beta-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Generate beta version
        id: beta-version
        run: |
          CURRENT_VERSION="${{ steps.current-version.outputs.current-version }}"
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*//')

          # Get the latest release to determine next build number
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r '.[0].tag_name // "v0.0.0"')
          echo "Latest release: $LATEST_RELEASE"

          # Extract build number from latest release or start from 1
          # Handle both old timestamp format and new semantic format
          if [[ $LATEST_RELEASE =~ v${BASE_VERSION}-(alpha|beta)\.([0-9]+) ]]; then
            BUILD_NUMBER=$(( ${BASH_REMATCH[2]} + 1 ))
          elif [[ $LATEST_RELEASE =~ v${BASE_VERSION}-(alpha|beta)\.([0-9]{14}) ]]; then
            # Old timestamp format - start from 1
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=1
          fi

          BETA_VERSION="${BASE_VERSION}-beta.${BUILD_NUMBER}"
          echo "beta-version=$BETA_VERSION" >> $GITHUB_OUTPUT
          echo "Beta version: $BETA_VERSION"

      - name: Update package.json version
        run: |
          npm version ${{ steps.beta-version.outputs.beta-version }} --no-git-tag-version
          echo "Updated package.json to version ${{ steps.beta-version.outputs.beta-version }}"

      - name: Upload version files
        uses: actions/upload-artifact@v4
        with:
          name: version-files
          path: |
            package.json
            package-lock.json

  build-linux:
    runs-on: ubuntu-latest
    needs: prepare-beta
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download version files
        uses: actions/download-artifact@v4
        with:
          name: version-files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build application (Linux)
        run: npm run build:linux-x64

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: |
            dist/*.AppImage
            dist/*.yml
            dist/*.blockmap

  build-windows:
    runs-on: windows-latest
    needs: prepare-beta
    env:
      # Force code signing for PR builds
      CSC_FOR_PULL_REQUEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download version files
        uses: actions/download-artifact@v4
        with:
          name: version-files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Self-Signed Certificate
        run: |
          # Create certificates directory
          mkdir -p certificates

          # Generate self-signed certificate
          openssl req -x509 -newkey rsa:2048 -keyout certificates/cert-key.pem -out certificates/cert.pem -days 365 -nodes -subj "/C=US/ST=CA/L=San Francisco/O=Comic Universe/CN=Comic Universe"

          # Convert to PKCS#12 format
          openssl pkcs12 -export -out certificates/cert.p12 -inkey certificates/cert-key.pem -in certificates/cert.pem -name "Comic Universe" -passout pass:comicuniverse

          # Set environment variables for electron-builder
          echo "CSC_LINK=certificates/cert.p12" >> $env:GITHUB_ENV
          echo "CSC_KEY_PASSWORD=comicuniverse" >> $env:GITHUB_ENV

      - name: Build application (Windows)
        run: npm run build:win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap

  build-macos:
    runs-on: macos-latest
    needs: prepare-beta
    env:
      # Force code signing for PR builds
      CSC_FOR_PULL_REQUEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download version files
        uses: actions/download-artifact@v4
        with:
          name: version-files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Self-Signed Certificate
        run: |
          # Create certificates directory
          mkdir -p certificates

          # Generate self-signed certificate
          openssl req -x509 -newkey rsa:2048 -keyout certificates/cert-key.pem -out certificates/cert.pem -days 365 -nodes -subj "/C=US/ST=CA/L=San Francisco/O=Comic Universe/CN=Comic Universe"

          # Convert to PKCS#12 format
          openssl pkcs12 -export -out certificates/cert.p12 -inkey certificates/cert-key.pem -in certificates/cert.pem -name "Comic Universe" -passout pass:comicuniverse

          # Set environment variables for electron-builder
          echo "CSC_LINK=certificates/cert.p12" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=comicuniverse" >> $GITHUB_ENV

      - name: Build application (macOS)
        run: npm run build:mac

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: |
            dist/*.dmg
            dist/*.yml
            dist/*.blockmap

  beta-release:
    runs-on: ubuntu-latest
    needs: [prepare-beta, build-linux, build-windows, build-macos]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate release notes
        run: |
          # Get the base branch commit to compare against
          BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
          HEAD_COMMIT="${{ github.event.pull_request.head.sha }}"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "## 🧪 Beta Release for PR #${{ github.event.number }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "This is a beta release created automatically for testing purposes." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "**PR:** #${{ github.event.number }}" >> $GITHUB_ENV
          echo "**Branch:** \`${{ github.head_ref }}\`" >> $GITHUB_ENV
          echo "**Target:** \`${{ github.base_ref }}\`" >> $GITHUB_ENV
          echo "**Auto-cleanup:** This release will be automatically deleted if PR #${{ github.event.number }} is closed without merging." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Changes" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          ./scripts/generate-release-notes.sh $BASE_COMMIT $HEAD_COMMIT >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Testing" >> $GITHUB_ENV
          echo "Please test this beta release and provide feedback in the PR comments." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Installation" >> $GITHUB_ENV
          echo "Download the appropriate build for your platform from the assets below." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Code Signing" >> $GITHUB_ENV
          echo "All builds are automatically signed with self-signed certificates. Users may see security warnings - this is normal for self-signed certificates." >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create beta release
        uses: softprops/action-gh-release@v2
        continue-on-error: false
        with:
          tag_name: 'v${{ needs.prepare-beta.outputs.version }}'
          name: 'Beta Release ${{ needs.prepare-beta.outputs.version }}'
          target_commitish: ${{ github.event.pull_request.head.sha }}
          body: ${{ env.RELEASE_NOTES }}
          files: |
            linux-builds/*
            windows-builds/*
            macos-builds/*
          draft: false
          prerelease: true
          generate_release_notes: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧪 **Beta Release Created**
              
              Version: \`${{ needs.prepare-beta.outputs.version }}\`
              
              A beta release has been created for testing this PR. You can download it from the [releases page](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.prepare-beta.outputs.version }}).
              
              Please test the beta release and provide feedback in the comments below.`
            })
