name: Beta Release (Pull Requests)

on:
  pull_request:
    branches:
      - main
      - staging
      - 'dev/v2.0.0'
    types: [opened, synchronize, reopened]

jobs:
  beta-release:
    runs-on: ubuntu-latest
    # Only run if this is the latest commit (prevents multiple releases for same PR)
    if: github.event.pull_request.head.sha == github.sha
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check CI status
        run: |
          # Check if CI has passed for this commit
          echo "Checking CI status for commit: ${{ github.event.pull_request.head.sha }}"
          # This is a simple check - in a real scenario, you might want to use the GitHub API
          # For now, we'll proceed and let the build process fail if there are issues
          echo "Proceeding with release creation..."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Generate beta version
        id: beta-version
        run: |
          CURRENT_VERSION="${{ steps.current-version.outputs.current-version }}"
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*//')
          BETA_VERSION="${BASE_VERSION}-beta.$(date +%Y%m%d%H%M%S)"
          echo "beta-version=$BETA_VERSION" >> $GITHUB_OUTPUT
          echo "Beta version: $BETA_VERSION"

      - name: Update package.json version
        run: |
          npm version ${{ steps.beta-version.outputs.beta-version }} --no-git-tag-version
          echo "Updated package.json to version ${{ steps.beta-version.outputs.beta-version }}"

      - name: Build application (Linux)
        run: |
          npm run build:linux-x64

      - name: Build application (Windows)
        run: |
          npm run build:win

      - name: Build application (macOS)
        run: |
          npm run build:mac

      - name: Create beta release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v${{ steps.beta-version.outputs.beta-version }}'
          name: 'Beta Release ${{ steps.beta-version.outputs.beta-version }}'
          body: |
            ## 🧪 Beta Release for PR #${{ github.event.number }}

            This is a beta release created automatically for testing purposes.

            **PR:** #${{ github.event.number }}
            **Branch:** `${{ github.head_ref }}`
            **Target:** `${{ github.base_ref }}`

            ## Changes
            ${{ github.event.pull_request.body }}

            ## Testing
            Please test this beta release and provide feedback in the PR comments.

            ## Installation
            Download the appropriate build for your platform from the assets below.
          files: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.exe
            dist/*.dmg
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧪 **Beta Release Created**
              
              Version: \`${{ steps.beta-version.outputs.beta-version }}\`
              
              A beta release has been created for testing this PR. You can download it from the [releases page](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.beta-version.outputs.beta-version }}).
              
              Please test the beta release and provide feedback in the comments below.`
            })
