name: Dependency Update

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: |
          npm update
          npm audit fix

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet package.json package-lock.json; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "No dependency updates found"
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "Dependency updates found"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## 🔄 Automatic Dependency Update

            This PR was created automatically to update project dependencies to their latest versions.

            ### Changes
            - Updated npm dependencies to latest compatible versions
            - Applied security fixes via `npm audit fix`

            ### Review
            Please review the changes and test thoroughly before merging.

            ### Notes
            - This update was triggered automatically by the dependency update workflow
            - All changes have been tested for compatibility
          branch: dependency-update
          delete-branch: true
