name: Dev Release

on:
  pull_request:
    branches:
      - staging
      - dev/v2.0.0

jobs:
  prepare-development:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      release-type: ${{ steps.version.outputs.release-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Generate version
        id: version
        run: |
          # Get the latest stable release to determine base version
          LATEST_STABLE_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r '.[] | select(.prerelease == false) | .tag_name' | head -1)
          echo "Latest stable release: $LATEST_STABLE_RELEASE"
          
          # Extract version from stable release (remove 'v' prefix)
          if [[ $LATEST_STABLE_RELEASE =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            STABLE_VERSION="${BASH_REMATCH[1]}"
            echo "Stable version: $STABLE_VERSION"
            
            # Increment patch version for next development cycle
            # If stable is 2.0.0, next dev should be 2.0.1-dev.X
            NEW_BASE_VERSION=$(echo $STABLE_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "New base version for dev: $NEW_BASE_VERSION"
          else
            # Fallback to current version if no stable release found
            CURRENT_VERSION="${{ steps.current-version.outputs.current-version }}"
            BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*//')
            NEW_BASE_VERSION=$(echo $BASE_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "Fallback: Using current version $CURRENT_VERSION, new base: $NEW_BASE_VERSION"
          fi

          # Get the latest development release for this base version to determine build number
          LATEST_DEV_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r ".[] | select(.tag_name | contains(\"${NEW_BASE_VERSION}-dev.\")) | .tag_name" | head -1)
          echo "Latest development release for $NEW_BASE_VERSION: $LATEST_DEV_RELEASE"

          # Extract build number from latest development release or start from 1
          if [[ $LATEST_DEV_RELEASE =~ v${NEW_BASE_VERSION}-dev\.([0-9]+) ]]; then
            # Increment build number
            BUILD_NUMBER=$(( ${BASH_REMATCH[1]} + 1 ))
            echo "Incrementing build number to: $BUILD_NUMBER"
          else
            # No existing dev release for this base version, start from 1
            BUILD_NUMBER=1
            echo "Starting new dev series with build number: $BUILD_NUMBER"
          fi

          # Create development version
          NEW_VERSION="${NEW_BASE_VERSION}-dev.${BUILD_NUMBER}"
          RELEASE_TYPE="development"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "release-type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"
          echo "Release type: $RELEASE_TYPE"

      - name: Update package.json version
        run: |
          # Use jq to update package.json directly to preserve 4-digit padding
          jq --arg version "${{ steps.version.outputs.version }}" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
          echo "Updated package.json to version ${{ steps.version.outputs.version }}"

      - name: Upload version files
        uses: actions/upload-artifact@v4
        with:
          name: version-files
          path: |
            package.json
            package-lock.json

  build-linux:
    runs-on: ubuntu-latest
    needs: prepare-development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download version files
        uses: actions/download-artifact@v4
        with:
          name: version-files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build application (Linux)
        run: npm run build:linux-x64

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: |
            dist/*.AppImage
            dist/*.yml
            dist/*.blockmap

  build-windows:
    runs-on: windows-latest
    needs: prepare-development
    env:
      # Code signing disabled for all builds
      CSC_FOR_PULL_REQUEST: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download version files
        uses: actions/download-artifact@v4
        with:
          name: version-files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # Code signing disabled for all builds
      # - name: Setup Consistent Certificate from Secrets

      - name: Build application (Windows)
        run: npm run build:win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap

  build-macos:
    runs-on: macos-latest
    needs: prepare-development
    env:
      # Code signing disabled for all builds
      CSC_FOR_PULL_REQUEST: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download version files
        uses: actions/download-artifact@v4
        with:
          name: version-files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # Code signing disabled for all builds
      # - name: Setup Consistent Certificate from Secrets

      - name: Build application (macOS)
        run: npm run build:mac

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.yml
            dist/*.blockmap

  create-release:
    runs-on: ubuntu-latest
    needs: [prepare-development, build-linux, build-windows, build-macos]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate release notes
        run: |
          # Get the base commit for comparison
          BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
          HEAD_COMMIT="${{ github.event.pull_request.head.sha }}"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "## 🔧 Dev Release for PR #${{ github.event.number }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "This is a dev release created automatically for early testing." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "**PR:** #${{ github.event.number }}" >> $GITHUB_ENV
          echo "**Branch:** \`${{ github.head_ref }}\`" >> $GITHUB_ENV
          echo "**Target:** \`${{ github.base_ref }}\`" >> $GITHUB_ENV
          echo "**Auto-cleanup:** This release will be automatically deleted if PR #${{ github.event.number }} is closed without merging." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Changes" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          ./scripts/generate-release-notes.sh $BASE_COMMIT $HEAD_COMMIT >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Testing" >> $GITHUB_ENV
          echo "Please test this dev release and provide feedback in the PR comments." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Installation" >> $GITHUB_ENV
          echo "Download the appropriate build for your platform from the assets below." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Code Signing" >> $GITHUB_ENV
          echo "Code signing is disabled for all builds to speed up the build process and avoid certificate issues." >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create dev release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          tag_name: 'v${{ needs.prepare-development.outputs.version }}'
          name: 'Dev Release ${{ needs.prepare-development.outputs.version }}'
          target_commitish: ${{ github.event.pull_request.head.sha }}
          body: ${{ env.RELEASE_NOTES }}
          files: |
            linux-builds/*
            windows-builds/*
            macos-builds/*
          draft: false
          prerelease: true
          generate_release_notes: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔧 **Dev Release Created**
              
              Version: \`${{ needs.prepare-development.outputs.version }}\`
              
              A dev release has been created for testing this PR. You can download it from the [releases page](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.prepare-development.outputs.version }}).
              
              Please test the dev release and provide feedback in the comments below.`
            })
